import {stripMigrationTransaction} from './sql-statements';
import { readFile, writeFile } from 'node:fs/promises';
export async function financeSchemaSQL(){
 const names=['001_initial_schema','002_add_wallets','003_ledger_integrity','004_financial_operations','005_rebuildable_balances','006_financial_workflows'];
 const sqls=await Promise.all(names.map(n=>readFile(`supabase/migrations/${n}.sql`,'utf8')));
 const body=sqls.map((sql,i)=>{
   let transformed=stripMigrationTransaction(sql).replace(/\bpublic\./g,'finance.').replace(/search_path\s*=\s*public/g,'search_path = finance').replace(/schemaname='public'/g,"schemaname='finance'");
   if(i===0)transformed=transformed.replace(/create or replace trigger on_auth_user_created\s+after insert on auth.users\s+for each row execute procedure finance.handle_new_user\(\);/,'-- No auth.users trigger: profile provisioning is explicit after verified login.');
   return `-- Source: ${names[i]}\n${transformed}`;
 }).join('\n');
 return `-- REVIEW ONLY. Never apply the public-schema migrations to an existing incompatible project.\n-- This transaction refuses an existing finance schema and never alters public/auth objects.\nbegin;\ncreate schema finance;\nset local search_path = finance, pg_catalog;\n${body}\n-- Remove the unused signup function: this bundle attaches no auth trigger.\ndrop function finance.handle_new_user();\n-- Close inherited/default privileges on new objects; opening API access is a separate reviewed step.\nrevoke all on schema finance from public, anon, authenticated, service_role;\nrevoke all on all tables in schema finance from public, anon, authenticated, service_role;\nrevoke all on all sequences in schema finance from public, anon, authenticated, service_role;\nrevoke all on all functions in schema finance from public, anon, authenticated, service_role;\n-- Make owner checks explicit on both sides of updates.\nalter policy "Users can update own profile" on finance.profiles with check (auth.uid()=id);\nalter policy "Users can manage own accounts" on finance.accounts with check (auth.uid()=user_id);\nalter policy "Users can manage own categories" on finance.categories with check (auth.uid()=user_id);\nalter policy "Users can manage own wallets" on finance.wallets with check (auth.uid()=user_id);\nalter policy "Users can manage own budgets" on finance.budgets with check (auth.uid()=user_id);\nalter policy "Users can manage own recurring transactions" on finance.recurring_transactions with check (auth.uid()=user_id);\ncommit;\n`;
}
if(process.argv[1]?.endsWith('build-finance-schema.ts'))void financeSchemaSQL().then(sql=>writeFile('supabase/compatibility/finance-isolated.sql',sql));
